elasticsearch:
  name: elasticsearch
  image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
  replicas: 1
  containerPort: 9200
  discoveryType: single-node
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"  

elasticsearchservice:
  name: elasticsearch-service
  serviceType: NodePort
  port: 9200
  targetPort: 9200
