ioeventCockpitApi:
  name: ioevent-cockpit-api
  image: jesserabidelli/cockpit:1.0.5
  replicas: 1
  containerPort: 8761
  esUrl: http://elasticsearch-service:9200
  kafkaBootstrapServer: my-cluster-kafka-bootstrap:9092
  kafkaGroupId: ioevent-cockpit-api
  readinessProbePath: /api/ping
  livenessProbePath: /api/ping
  readinessProbeInitialDelay: 30
  livenessProbeInitialDelay: 60
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "2"
  oauthClientId: 7a85924d095028b88070
  oauthClientSecret: 0ef177b2bf265fd9c0ec7856183151a105a58cb2
  oauthAccessTokenUri: https://github.com/login/oauth/access_token
  oauthUserInfoUri: https://api.github.com/user
  oauthPreferredUsername: login
  oauthEmail: email
  oauthRedirectUri: http://localhost:3000/pages/auth/sso
ioeventCockpitApiService:
  name: ioevent-cockpit-api-service
  serviceType: LoadBalancer
  port: 8761
  targetPort: 8761
  
