apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.elasticsearch.name }}
spec:
  replicas: {{ .Values.elasticsearch.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.elasticsearch.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.elasticsearch.name }}
    spec:
      containers:
      - name: {{ .Values.elasticsearch.name }}
        image: {{ .Values.elasticsearch.image }}
        env:
        - name: discovery.type
          value: {{ .Values.elasticsearch.discoveryType }}
        - name: xpack.security.enabled
          value: "false"
        - name: xpack.security.enrollment.enabled
          value: "false"
        resources:
          requests:
            cpu: "{{ .Values.elasticsearch.resources.requests.cpu }}"
            memory: "{{ .Values.elasticsearch.resources.requests.memory }}"
          limits:
            cpu: "{{ .Values.elasticsearch.resources.limits.cpu }}"
            memory: "{{ .Values.elasticsearch.resources.limits.memory }}"
        ports:
        - containerPort: {{ .Values.elasticsearch.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticsearchservice.name }}
spec:
  type: {{ .Values.elasticsearchservice.serviceType }}
  ports:
    - port: {{ .Values.elasticsearchservice.port }}
      targetPort: {{ .Values.elasticsearchservice.targetPort }}
  selector:
    app: {{ .Values.elasticsearch.name }}