ioeventui:
  name: ioeventui
  image: ioevent/cockpit-ui:latest
  replicas: 1
  containerPort: 3000
  apiUrl: "http://k8s-helmchar-ioeventc-c652dc5b90-4d2ec304b475194c.elb.eu-central-1.amazonaws.com:8761/api"
  uiRegistration: "true#####"
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "2"

ioeventuiservice:
  name: ioeventui-service
  port: 3000
  targetPort: 3000
  serviceType: LoadBalancer