ioeventui:
  name: ioeventui
  image: ioevent/cockpit-ui:latest
  replicas: 1
  containerPort: 3000
  apiUrl: "http://k8s-helmchar-ioeventc-397aeb6875-28e4364c32943822.elb.eu-central-1.amazonaws.com:8761/api"
  uiRegistration: "true#####"
  resources:
    requests:
      memory: "3Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"

ioeventuiservice:
  name: ioeventui-service
  port: 3000
  targetPort: 3000
  serviceType: LoadBalancer