ioeventui:
  name: ioeventui
  image: jesserabidelli/cockpitui:1.0.2
  replicas: 1
  containerPort: 3000
  apiUrl: "http://k8s-helmchar-ioeventc-b0c2c1a3c2-213c24b19b8a8a80.elb.eu-central-1.amazonaws.com:8761/api"
  uiRegistration: "true#####"
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
      cpu: "2"
  enableSSO: "true"
  ssoUrl: https://github.com/login/oauth/authorize
  clientId: 7a85924d095028b88070
  redirectUri: http://localhost:3000/pages/auth/sso
  responseType: code

ioeventuiservice:
  name: ioeventui-service
  port: 3000
  targetPort: 3000
  serviceType: LoadBalancer
