ioeventui:
  name: ioeventui
  image: ioevent/cockpit-ui:latest
  replicas: 1
  containerPort: 3000
  apiUrl: "k8s-default-ioeventc-ee2b469321-45be3fe7dcf074c9.elb.eu-central-1.amazonaws.com:8761/api"
  uiRegistration: "true#####"
  resources:
    requests:
      memory: "3Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"

ioeventuiservice:
  name: ioeventui-service
  port: 3000
  targetPort: 3000
  serviceType: LoadBalancer