kafka:
  name: my-cluster
  version: 3.6.1
  replicas: 1
  plainListenerPort: 9092
  tlsListenerPort: 9093
  externalListenerPort: 9094
  listenerType: nodeport
  offsetsReplicationFactor: 1
  transactionReplicationFactor: 1
  transactionMinIsr: 1
  defaultReplicationFactor: 1
  minInsyncReplicas: 1
  interBrokerProtocolVersion: "3.6"
  storageType: ephemeral
  livenessProbeInitialDelay: 60
  livenessProbeTimeout: 5
  readinessProbeInitialDelay: 60
  readinessProbeTimeout: 5

zookeeper:
  replicas: 1
  storageType: ephemeral
  livenessProbeInitialDelay: 300
  livenessProbeTimeout: 5
  readinessProbeInitialDelay: 300
  readinessProbeTimeout: 5


elasticsearch:
  name: elasticsearch
  image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
  replicas: 1
  containerPort: 9200
  discoveryType: single-node

elasticsearchservice:
  name: elasticsearch-service
  serviceType: NodePort
  port: 9200
  targetPort: 9200
