apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.elasticsearch.name }}
spec:
  replicas: {{ .Values.elasticsearch.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.elasticsearch.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.elasticsearch.name }}
    spec:
      containers:
      - name: {{ .Values.elasticsearch.name }}
        image: {{ .Values.elasticsearch.image }}
        env:
        - name: discovery.type
          value: {{ .Values.elasticsearch.discoveryType }}
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        ports:
        - containerPort: {{ .Values.elasticsearch.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticsearchservice.name }}
spec:
  type: {{ .Values.elasticsearchservice.serviceType }}
  ports:
    - port: {{ .Values.elasticsearchservice.port }}
      targetPort: {{ .Values.elasticsearchservice.targetPort }}
  selector:
    app: {{ .Values.elasticsearch.name }}